language: php

dist:
- xenial
- trusty

php:
- '7.3'
- '5.0'

services:
- mariadb

jobs:
  fast_finish: true
  include:
  - dist: xenial
    php: '7.3'
  - dist: trusty
    php: '5.0'

env:
- WP_VERSION=5.2
- WP_VERSION=4.0

before_install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
