language: php
dist: xenial

php:
- '7.1'
- '7.2'
- '7.4'

services:
- mysql

cache:
  directories:
  - $HOME/.composer/cache/files

env:
- WP_VERSION=5.0
- WP_VERSION=5.2
- WP_VERSION=5.4

install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install

script: composer run test
