language: php
dist: xenial

# they are the active versions listed on https://www.php.net/
php:
- '7.2'
- '7.3'
- '7.4'

services:
- mysql

cache:
  directories:
  - $HOME/.composer/cache/files

env:
- WP_VERSION=5.3
- WP_VERSION=5.4
- WP_VERSION=5.5

install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install

script: composer run test
