language: php
php: '7.3'
cache:
  directories:
    - $HOME/.composer/cache/files

env:
- WP_VERSION=5.2
- WP_VERSION=4.0

install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
