language: php

php:
- '5.6'
- '5.5'
- '5.4'
- '5.3'

env:
- WP_VERSION=4.0
- WP_VERSION=3.9.2
- WP_VERSION=3.8.4
- WP_VERSION=3.7.4
- WP_VERSION=3.6.1
- WP_VERSION=3.5.2

install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
