language: php
php:
- '7.3'
- '6'
- '5'
cache:
  directories:
  - $HOME/.composer/cache/files

services:
- mariadb

env:
- WP_VERSION=5.2
- WP_VERSION=4.0

before_install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
