language: php

php: '7.3'

services:
- mysql

jobs:
  fast_finish: true

env:
- WP_VERSION=5.2
- WP_VERSION=4.0

before_install:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer run test
