version: '3'

services:
  mysql:

    image: mariadb:latest
    restart: always
    ports:
    - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: pass
